### ISSUE TITLE
new site for ms-vscode project 

### ISSUE THREAD

**Issue by SpudGunMan** [maarten-pennings/Lego-Mindstorms#2]
https://github.com/PeterStaev/lego-spikeprime-mindstorms-vscode

this is worth adding to your kb

**Comment by maarten-pennings** [comment]
I just gave it a try, but I really need a tutorial....

**Comment by SpudGunMan** [comment]
https://marketplace.visualstudio.com/items?itemName=PeterStaev.lego-spikeprime-mindstorms-vscode

has some how to?

**Comment by maarten-pennings** [comment]
Added
