### ISSUE TITLE
debug mode on lego app /osx

### ISSUE THREAD

**Issue by SpudGunMan** [maarten-pennings/Lego-Mindstorms#3]
`cd ~/Library/Containers/com.lego.retail.mindstorms.robotinventor/Data/Library/Application\ Support/MINDSTORMS_ROBOTINVENTOR/`

userSettings.json
Go to the end of the line/file, and add the following string properly:    `   ,"ui.debug":true}`
Mind the quote style and adding it into the json format to function. 
Debug menu and new debug block functions to add

**Comment by SpudGunMan** [comment]
works for windows as well but path will be different

**Comment by maarten-pennings** [comment]
thx, added
