### ISSUE TITLE
Info: Spike with µPIDE

### ISSUE THREAD

**Issue by harbaum** [maarten-pennings/Lego-Mindstorms#4]
You describe how to use the right COM port and a terminal program. That's totally fine. But a way easier solution ist to run an IDE like [µPIDE](https://github.com/harbaum/upide).

It works out of the box with the spike. It's auto detected (no com port fiddling) and you can browse the spikes file system, up- and download files and use REPL.

**Comment by maarten-pennings** [comment]
Hi, I just gave it a try. My Lego Robot Inventor Hub was connected via USB, and switched on. It was shown as COM3 in device manager. But uPIDE didn't find it. What should I do?

![image](https://user-images.githubusercontent.com/30388931/159368268-b3d0d836-c7f7-41d4-b60e-77b13bf1d43a.png)

**Comment by maarten-pennings** [comment]
I think uPIDE was already running in a small window behind my browser, preventing the second one to reach the COM port.
Thanks. I will give it a try (and I added it to the FAQ).

**Comment by harbaum** [comment]
Yeah, I sometimes also have this effect that the window opens behind other windows. That only happens under Windows and I have yet to see a pattern for how and when this happens.
